export type DistrictDirectoryEntry = {
  number: number
  name: string
  dcmName: string | null
  dcmEmail: string | null
  counties: string[]
  cities?: string[]
  website?: string
  description?: string
  note?: string
  unrepresented?: boolean
  linguistic?: boolean
  meetingDay?: string
  meetingTime?: string | null
  meetingLocation?: string
  meetingAddress?: string
  meetingNote?: string
}

export const districtDirectory: DistrictDirectoryEntry[] = [
  {
    number: 1,
    name: "District 1",
    dcmName: "Collin R.",
    dcmEmail: "dist1@area36.org",
    counties: ["Olmsted", "Wabasha", "Goodhue", "Dodge (East)"],
    website: "www.aadistrict1.org",
    meetingDay: "3rd Wednesday",
    meetingTime: "6:30 PM",
    meetingLocation: "Various Locations",
    meetingNote: "Contact DCM for location",
  },
  {
    number: 2,
    name: "District 2",
    dcmName: "Steve B.",
    dcmEmail: "dist2@area36.org",
    counties: ["Fillmore", "Houston", "Winona"],
    website: "www.aadistrict2.org",
    meetingDay: "3rd Thursday",
    meetingTime: "7:00 PM",
    meetingLocation: "Grace Presbyterian Church",
    meetingAddress: "222 E. Broadway Street, Winona, MN 55987",
  },
  {
    number: 3,
    name: "District 3",
    dcmName: "Lynn S.",
    dcmEmail: "dist3@area36.org",
    counties: ["Freeborn", "Mower", "Steele", "Waseca", "Dodge (West)"],
    meetingDay: "1st Saturday",
    meetingTime: null,
    meetingLocation: "West Hills Alano",
    meetingAddress: "605 Florence Avenue, Owatonna, MN",
    meetingNote: "2nd Saturday if Area 36 event on 1st Saturday",
  },
  {
    number: 4,
    name: "District 4",
    dcmName: null,
    dcmEmail: null,
    counties: ["Meeker", "Kandiyohi"],
    unrepresented: true,
  },
  {
    number: 5,
    name: "District 5",
    dcmName: "Mort M.",
    dcmEmail: "dist5@area36.org",
    counties: ["Swift", "Chippewa", "Big Stone", "Lac Qui Parle"],
    website: "mndist5aa.wixsite.com/mndist5aa",
  },
  {
    number: 6,
    name: "District 6",
    dcmName: null,
    dcmEmail: null,
    counties: ["Yellow Medicine", "Lincoln", "Lyon"],
    unrepresented: true,
  },
  {
    number: 7,
    name: "District 7",
    dcmName: "Jaime M.",
    dcmEmail: "dist7@area36.org",
    counties: ["Hennepin (Southwest)"],
    cities: ["Chanhassen", "Eden Prairie", "Edina"],
    description: "Southwest Hennepin County including communities on the south shore of Lake Minnetonka",
    meetingDay: "2nd Monday",
    meetingTime: "6:30 PM",
    meetingLocation: "Immanuel Lutheran Church (Hybrid)",
    meetingAddress: "16515 Luther Way, Eden Prairie, MN 55346",
  },
  {
    number: 8,
    name: "District 8",
    dcmName: "Lindsey D.",
    dcmEmail: "dist8@area36.org",
    counties: ["Ramsey"],
    cities: ["St. Paul", "Maplewood", "White Bear Lake", "New Brighton", "Roseville", "Arden Hills"],
    meetingDay: "3rd Wednesday",
    meetingTime: "7:00 PM",
    meetingLocation: "On Zoom",
    meetingNote: "Contact DCM for Zoom information",
  },
  {
    number: 9,
    name: "District 9",
    dcmName: "Bennett C.",
    dcmEmail: "dist9@area36.org",
    counties: ["Blue Earth", "Le Sueur"],
    cities: ["Mankato", "North Mankato"],
    meetingDay: "2nd Tuesday",
    meetingTime: "7:00 PM",
    meetingAddress: "1430 5th Avenue, Mankato, MN 56001",
  },
  {
    number: 11,
    name: "District 11",
    dcmName: "Todd W.",
    dcmEmail: "dist11@area36.org",
    counties: ["Rock", "Pipestone", "Murray", "Nobles"],
    meetingLocation: "Sanford Hospital – Blue Mound Room",
    meetingAddress: "1600 N Kniss Ave, Luverne, MN 56156",
  },
  {
    number: 12,
    name: "District 12",
    dcmName: null,
    dcmEmail: "dist12@area36.org",
    counties: ["Cottonwood", "Watonwan", "Jackson", "Martin", "Faribault"],
    unrepresented: true,
    meetingDay: "3rd Monday",
    meetingTime: "7:00 PM",
    meetingLocation: "Senior Citizens Center",
    meetingAddress: "21 E 1st ST, Sherburn, MN 56171",
  },
  {
    number: 13,
    name: "District 13",
    dcmName: "Barbara H.",
    dcmEmail: "dist13@area36.org",
    counties: ["Anoka"],
    cities: ["NE Minneapolis"],
    meetingDay: "1st Tuesday",
    meetingTime: "7:00 PM",
    meetingLocation: "Coon Rapids United Methodist Church",
    meetingAddress: "10506 Hanson Blvd. N.W., Coon Rapids, MN 55433",
  },
  {
    number: 14,
    name: "District 14",
    dcmName: "Jon G.",
    dcmEmail: "dist14@area36.org",
    counties: ["Wright"],
    website: "district14area36aa.org",
    meetingDay: "1st Monday",
    meetingTime: "7:00 PM",
    meetingLocation: "Buffalo United Methodist Church",
    meetingAddress: "609 8th St NW, Buffalo, MN 55313",
  },
  {
    number: 15,
    name: "District 15",
    dcmName: "Matt T.",
    dcmEmail: "dist15@area36.org",
    counties: ["Washington"],
    website: "www.aadistrict15.org",
    meetingDay: "4th Monday",
    meetingTime: "7:00 PM",
    meetingLocation: "Christ Lutheran Church",
    meetingAddress: "11194 36th St, Lake Elmo, MN 55042",
  },
  {
    number: 16,
    name: "District 16",
    dcmName: "Tina D.",
    dcmEmail: "dist16@area36.org",
    counties: ["Rice"],
    meetingDay: "3rd Thursday",
    meetingTime: "7:00 PM",
    meetingLocation: "Faribault Alano Club",
    meetingAddress: "217 Central Ave, Faribault, MN 55021",
  },
  {
    number: 17,
    name: "District 17",
    dcmName: null,
    dcmEmail: "dist17@area36.org",
    counties: ["Carver", "McLeod", "Sibley"],
    unrepresented: true,
    website: "district17aa.net",
    meetingDay: "2nd Tuesday",
    meetingTime: "7:30 PM",
    meetingLocation: "Assembly of God Church",
    meetingAddress: "10478 Bell Ave, Plato, MN 55370",
  },
  {
    number: 18,
    name: "District 18",
    dcmName: "Michael L.",
    dcmEmail: "dist18@area36.org",
    counties: ["Hennepin"],
    description: "Minneapolis Inner Metro",
    meetingDay: "2nd Thursday",
    meetingTime: "6:30 PM",
    meetingLocation: "On Zoom",
    meetingNote: "Contact DCM for Zoom link",
  },
  {
    number: 19,
    name: "District 19",
    dcmName: "Val L.",
    dcmEmail: "dist19@area36.org",
    counties: ["Dakota"],
    meetingDay: "2nd Wednesday",
    meetingTime: "7:00 PM",
    meetingLocation: "Eagan Community Center",
    meetingAddress: "1501 Central Pkwy, Eagan, MN 55121",
  },
  {
    number: 20,
    name: "District 20",
    dcmName: "Kathleen F.",
    dcmEmail: "dist20@area36.org",
    counties: ["Hennepin (Northwest)"],
    cities: ["Champlin", "Brooklyn Park", "Brooklyn Center", "New Hope", "Crystal", "Robbinsdale"],
    website: "district20area36aa.org",
    meetingDay: "4th Tuesday",
    meetingTime: "7:00 PM",
    meetingLocation: "Twin Lakes Alano Society",
    meetingAddress: "4938 Brooklyn Blvd, Brooklyn Center, MN 55429",
  },
  {
    number: 21,
    name: "District 21",
    dcmName: "Micheala Q.",
    dcmEmail: "dist21@area36.org",
    counties: ["Hennepin (West)"],
    description: "Crow River to west, Hwy 169 to east, Minnetonka to south (including Minnetonka Beach, Orono, Independence)",
    meetingDay: "2nd Tuesday",
    meetingTime: "7:00 PM",
    meetingLocation: "Pilgrim Methodist Church",
    meetingAddress: "4325 Zachary Lane, Plymouth, MN 55441",
  },
  {
    number: 22,
    name: "District 22",
    dcmName: "Kyle A.",
    dcmEmail: "dist22@area36.org",
    counties: ["Hennepin"],
    cities: ["Golden Valley", "St. Louis Park", "Minnetonka"],
    website: "www.district22mn.com",
    description: "Excludes quadrant NW of Hwy 169 & I-394 (District 21)",
    meetingDay: "2nd Wednesday",
    meetingTime: "7:00 PM",
    meetingLocation: "Vista Lutheran Church",
    meetingAddress: "4003 Woodale Ave, Saint Louis Park, MN 55416",
  },
  {
    number: 23,
    name: "District 23",
    dcmName: "Vernon M.",
    dcmEmail: "dist23@area36.org",
    counties: ["Brown", "Nicollet", "Redwood", "Renville"],
    website: "dist23.net",
    note: "Incorporated District 10 in November 2022",
    meetingDay: "3rd Thursday",
    meetingTime: "7:00 PM",
    meetingLocation: "River Valley Church",
    meetingAddress: "100 N Washington, New Ulm, MN 56073",
  },
  {
    number: 24,
    name: "District 24",
    dcmName: "Steve B.",
    dcmEmail: "dist24@area36.org",
    counties: ["Scott"],
    cities: ["Carver", "Chaska", "Shakopee", "Prior Lake", "Savage"],
    meetingDay: "1st Wednesday",
    meetingTime: "6:30 PM",
    meetingLocation: "Shakopee Community Center (Hybrid)",
    meetingAddress: "1255 Fuller St S, Shakopee, MN 55379",
  },
  {
    number: 25,
    name: "District 25",
    dcmName: "Holly S.",
    dcmEmail: "dist25@area36.org",
    counties: ["Hennepin (South)"],
    cities: ["Richfield", "Bloomington"],
    meetingDay: "2nd Wednesday",
    meetingTime: "7:30 PM",
    meetingLocation: "Woodlake Lutheran Church",
    meetingAddress: "7525 Oliver Ave S, Richfield, MN 55423",
  },
  {
    number: 26,
    name: "District 26",
    dcmName: null,
    dcmEmail: null,
    counties: ["Ramsey (partial)"],
    description: "Maryland Ave to north, I-35E to west, Hwy 52 to southwest, Mississippi River to south",
    unrepresented: true,
    meetingDay: "2nd Friday",
    meetingTime: "6:00 PM",
    meetingLocation: "East Side Alano Club",
    meetingAddress: "1099 Payne Ave, St Paul, MN 55130",
  },
  {
    number: 27,
    name: "District 27",
    dcmName: "Elias J.",
    dcmEmail: "dist27@area36.org",
    counties: ["All of Area 36"],
    description: "Spanish-speaking groups throughout Area 36",
    linguistic: true,
    meetingDay: "2nd Saturday",
    meetingTime: "5:30 PM",
    meetingLocation: "Recovery Church",
    meetingAddress: "253 S. State St, Saint Paul, MN",
    meetingNote: "Spanish speaking, LGBTQ+ friendly, child friendly, wheelchair accessible",
  },
]

