-- Seed initial events with approved status
INSERT INTO events (id, title, date, end_date, time, location, description, type, status, submitter_email, created_at, updated_at)
VALUES
  ('evt_001', 'West Central Region Forum', '2025-09-19', '2025-09-21', '5:00 PM - 12:00 PM', 'Hilton Hotel, Omaha, Nebraska', 'Area 41 hosts the West Central Region Forum. A great opportunity to meet A.A. members from across the region.', 'Regional', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_002', 'Area Assembly – Budget (Hybrid)', '2025-10-18', NULL, '9:00 AM - 4:00 PM', 'Jordan Community Center, 500 Sunset Drive, Suite #19, Jordan, MN 55352', 'Budget assembly with hybrid attendance options. All GSRs encouraged to attend.', 'Assembly', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_003', '2025 Area 35/36 Joint Corrections Workshop', '2025-10-25', NULL, '9:30 AM - 3:30 PM', 'TBA', 'Joint workshop with Area 35 focused on corrections service. Learn how to carry the message to those in treatment and correctional facilities.', 'Workshop', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_004', 'Area Inventory', '2025-11-08', NULL, '9:00 AM - 1:00 PM', 'Wyndham, 14201 Nicollet Ave, Burnsville, MN 55337', 'Annual area inventory meeting. An opportunity to reflect on how we can better serve the fellowship.', 'Meeting', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_005', 'Area Committee Meeting Annual Meeting (Online)', '2025-12-06', NULL, '9:30 AM - 5:00 PM', 'Online', 'Committees 9:30 – 11:30 am, GSR/Alts 10:30 – 11:30 (Optional), Area Committee 12:30 – 5:00 pm', 'Committee', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_006', 'Spring Assembly', '2026-03-21', NULL, '9:00 AM - 4:00 PM', 'TBA', 'Spring assembly for Area 36. Topics and location to be announced.', 'Assembly', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_007', 'District 5 Monthly Meeting', '2025-10-12', NULL, '2:00 PM - 4:00 PM', 'First Lutheran Church, Rochester, MN', 'Monthly district meeting. All GSRs and interested members welcome.', 'District', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_008', 'District 12 Fall Workshop', '2025-11-15', NULL, '10:00 AM - 2:00 PM', 'Community Center, Mankato, MN', 'Workshop on sponsorship and service. Lunch provided.', 'District', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_009', 'District 8 Planning Meeting', '2025-10-26', NULL, '1:00 PM - 3:00 PM', 'Unity Church, Burnsville, MN', 'Planning session for upcoming district events and gratitude dinner.', 'District', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_010', 'District 3 Gratitude Dinner', '2025-11-22', NULL, '5:00 PM - 8:00 PM', 'American Legion, Faribault, MN', 'Annual gratitude dinner with speaker. Tickets $15, families welcome.', 'District', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_011', 'District 15 Service Workshop', '2025-12-07', NULL, '9:00 AM - 12:00 PM', 'St. Mary''s Church, Winona, MN', 'Introduction to service positions at group, district, and area levels.', 'District', 'approved', 'admin@area36.org', datetime('now'), datetime('now')),
  ('evt_012', 'District 9 Holiday Alcathon', '2025-12-25', NULL, '12:00 AM - 11:59 PM', 'Alano Club, Bloomington, MN', '24-hour marathon meetings on Christmas Day. Fellowship and food all day.', 'District', 'approved', 'admin@area36.org', datetime('now'), datetime('now'));
